# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.4

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/luca/C^4"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/luca/C^4"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/luca/C^4/CMakeFiles" "/home/luca/C^4//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/luca/C^4/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named intrinsics_gen

# Build rule for target.
intrinsics_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 intrinsics_gen
.PHONY : intrinsics_gen

# fast build rule for target.
intrinsics_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intrinsics_gen.dir/build.make CMakeFiles/intrinsics_gen.dir/build
.PHONY : intrinsics_gen/fast

#=============================================================================
# Target rules for targets named vt_gen

# Build rule for target.
vt_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vt_gen
.PHONY : vt_gen

# fast build rule for target.
vt_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vt_gen.dir/build.make CMakeFiles/vt_gen.dir/build
.PHONY : vt_gen/fast

#=============================================================================
# Target rules for targets named omp_gen

# Build rule for target.
omp_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 omp_gen
.PHONY : omp_gen

# fast build rule for target.
omp_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omp_gen.dir/build.make CMakeFiles/omp_gen.dir/build
.PHONY : omp_gen/fast

#=============================================================================
# Target rules for targets named acc_gen

# Build rule for target.
acc_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acc_gen
.PHONY : acc_gen

# fast build rule for target.
acc_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acc_gen.dir/build.make CMakeFiles/acc_gen.dir/build
.PHONY : acc_gen/fast

#=============================================================================
# Target rules for targets named target_parser_gen

# Build rule for target.
target_parser_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 target_parser_gen
.PHONY : target_parser_gen

# fast build rule for target.
target_parser_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/target_parser_gen.dir/build.make CMakeFiles/target_parser_gen.dir/build
.PHONY : target_parser_gen/fast

#=============================================================================
# Target rules for targets named qc

# Build rule for target.
qc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qc
.PHONY : qc

# fast build rule for target.
qc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/build
.PHONY : qc/fast

impl/compiler.o: impl/compiler.cpp.o
.PHONY : impl/compiler.o

# target to build an object file
impl/compiler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/impl/compiler.cpp.o
.PHONY : impl/compiler.cpp.o

impl/compiler.i: impl/compiler.cpp.i
.PHONY : impl/compiler.i

# target to preprocess a source file
impl/compiler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/impl/compiler.cpp.i
.PHONY : impl/compiler.cpp.i

impl/compiler.s: impl/compiler.cpp.s
.PHONY : impl/compiler.s

# target to generate assembly for a file
impl/compiler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/impl/compiler.cpp.s
.PHONY : impl/compiler.cpp.s

impl/compiler_run.o: impl/compiler_run.cpp.o
.PHONY : impl/compiler_run.o

# target to build an object file
impl/compiler_run.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/impl/compiler_run.cpp.o
.PHONY : impl/compiler_run.cpp.o

impl/compiler_run.i: impl/compiler_run.cpp.i
.PHONY : impl/compiler_run.i

# target to preprocess a source file
impl/compiler_run.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/impl/compiler_run.cpp.i
.PHONY : impl/compiler_run.cpp.i

impl/compiler_run.s: impl/compiler_run.cpp.s
.PHONY : impl/compiler_run.s

# target to generate assembly for a file
impl/compiler_run.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/impl/compiler_run.cpp.s
.PHONY : impl/compiler_run.cpp.s

impl/errors.o: impl/errors.cpp.o
.PHONY : impl/errors.o

# target to build an object file
impl/errors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/impl/errors.cpp.o
.PHONY : impl/errors.cpp.o

impl/errors.i: impl/errors.cpp.i
.PHONY : impl/errors.i

# target to preprocess a source file
impl/errors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/impl/errors.cpp.i
.PHONY : impl/errors.cpp.i

impl/errors.s: impl/errors.cpp.s
.PHONY : impl/errors.s

# target to generate assembly for a file
impl/errors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/impl/errors.cpp.s
.PHONY : impl/errors.cpp.s

impl/lexer.o: impl/lexer.cpp.o
.PHONY : impl/lexer.o

# target to build an object file
impl/lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/impl/lexer.cpp.o
.PHONY : impl/lexer.cpp.o

impl/lexer.i: impl/lexer.cpp.i
.PHONY : impl/lexer.i

# target to preprocess a source file
impl/lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/impl/lexer.cpp.i
.PHONY : impl/lexer.cpp.i

impl/lexer.s: impl/lexer.cpp.s
.PHONY : impl/lexer.s

# target to generate assembly for a file
impl/lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/impl/lexer.cpp.s
.PHONY : impl/lexer.cpp.s

impl/main.o: impl/main.cpp.o
.PHONY : impl/main.o

# target to build an object file
impl/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/impl/main.cpp.o
.PHONY : impl/main.cpp.o

impl/main.i: impl/main.cpp.i
.PHONY : impl/main.i

# target to preprocess a source file
impl/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/impl/main.cpp.i
.PHONY : impl/main.cpp.i

impl/main.s: impl/main.cpp.s
.PHONY : impl/main.s

# target to generate assembly for a file
impl/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/impl/main.cpp.s
.PHONY : impl/main.cpp.s

impl/nodes.o: impl/nodes.cpp.o
.PHONY : impl/nodes.o

# target to build an object file
impl/nodes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/impl/nodes.cpp.o
.PHONY : impl/nodes.cpp.o

impl/nodes.i: impl/nodes.cpp.i
.PHONY : impl/nodes.i

# target to preprocess a source file
impl/nodes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/impl/nodes.cpp.i
.PHONY : impl/nodes.cpp.i

impl/nodes.s: impl/nodes.cpp.s
.PHONY : impl/nodes.s

# target to generate assembly for a file
impl/nodes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/impl/nodes.cpp.s
.PHONY : impl/nodes.cpp.s

impl/parser.o: impl/parser.cpp.o
.PHONY : impl/parser.o

# target to build an object file
impl/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/impl/parser.cpp.o
.PHONY : impl/parser.cpp.o

impl/parser.i: impl/parser.cpp.i
.PHONY : impl/parser.i

# target to preprocess a source file
impl/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/impl/parser.cpp.i
.PHONY : impl/parser.cpp.i

impl/parser.s: impl/parser.cpp.s
.PHONY : impl/parser.s

# target to generate assembly for a file
impl/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/impl/parser.cpp.s
.PHONY : impl/parser.cpp.s

impl/preproccesser.o: impl/preproccesser.cpp.o
.PHONY : impl/preproccesser.o

# target to build an object file
impl/preproccesser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/impl/preproccesser.cpp.o
.PHONY : impl/preproccesser.cpp.o

impl/preproccesser.i: impl/preproccesser.cpp.i
.PHONY : impl/preproccesser.i

# target to preprocess a source file
impl/preproccesser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/impl/preproccesser.cpp.i
.PHONY : impl/preproccesser.cpp.i

impl/preproccesser.s: impl/preproccesser.cpp.s
.PHONY : impl/preproccesser.s

# target to generate assembly for a file
impl/preproccesser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/impl/preproccesser.cpp.s
.PHONY : impl/preproccesser.cpp.s

impl/token.o: impl/token.cpp.o
.PHONY : impl/token.o

# target to build an object file
impl/token.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/impl/token.cpp.o
.PHONY : impl/token.cpp.o

impl/token.i: impl/token.cpp.i
.PHONY : impl/token.i

# target to preprocess a source file
impl/token.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/impl/token.cpp.i
.PHONY : impl/token.cpp.i

impl/token.s: impl/token.cpp.s
.PHONY : impl/token.s

# target to generate assembly for a file
impl/token.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/impl/token.cpp.s
.PHONY : impl/token.cpp.s

runtime_embed.o: runtime_embed.cpp.o
.PHONY : runtime_embed.o

# target to build an object file
runtime_embed.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/runtime_embed.cpp.o
.PHONY : runtime_embed.cpp.o

runtime_embed.i: runtime_embed.cpp.i
.PHONY : runtime_embed.i

# target to preprocess a source file
runtime_embed.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/runtime_embed.cpp.i
.PHONY : runtime_embed.cpp.i

runtime_embed.s: runtime_embed.cpp.s
.PHONY : runtime_embed.s

# target to generate assembly for a file
runtime_embed.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/runtime_embed.cpp.s
.PHONY : runtime_embed.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... acc_gen"
	@echo "... intrinsics_gen"
	@echo "... omp_gen"
	@echo "... target_parser_gen"
	@echo "... vt_gen"
	@echo "... qc"
	@echo "... impl/compiler.o"
	@echo "... impl/compiler.i"
	@echo "... impl/compiler.s"
	@echo "... impl/compiler_run.o"
	@echo "... impl/compiler_run.i"
	@echo "... impl/compiler_run.s"
	@echo "... impl/errors.o"
	@echo "... impl/errors.i"
	@echo "... impl/errors.s"
	@echo "... impl/lexer.o"
	@echo "... impl/lexer.i"
	@echo "... impl/lexer.s"
	@echo "... impl/main.o"
	@echo "... impl/main.i"
	@echo "... impl/main.s"
	@echo "... impl/nodes.o"
	@echo "... impl/nodes.i"
	@echo "... impl/nodes.s"
	@echo "... impl/parser.o"
	@echo "... impl/parser.i"
	@echo "... impl/parser.s"
	@echo "... impl/preproccesser.o"
	@echo "... impl/preproccesser.i"
	@echo "... impl/preproccesser.s"
	@echo "... impl/token.o"
	@echo "... impl/token.i"
	@echo "... impl/token.s"
	@echo "... runtime_embed.o"
	@echo "... runtime_embed.i"
	@echo "... runtime_embed.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

